/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manager capabilities
         * @description Versions and feature flags clients use to adapt to this manager.
         */
        get: operations["get-capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Reports that the manager process is serving requests. Used by the container HEALTHCHECK.
         */
        get: operations["get-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Reports whether the manager can serve traffic: the database is reachable and all migrations are applied. Returns 503 not_ready with one detail per failing check otherwise.
         */
        get: operations["get-health-ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CapabilitiesBody: {
            /** @example dockyard.agent/v1 */
            agentProtocolVersion: string;
            /** @example v1 */
            apiVersion: string;
            /** @description Stable feature-flag keys enabled on this manager. */
            features: string[];
            /** @example 0.0.0-edge */
            managerVersion: string;
        };
        Error: {
            /**
             * @description Stable snake_case error code; switch on this, not on message.
             * @example not_found
             */
            code: string;
            /** @description Per-field problems, empty when not applicable. */
            details: components["schemas"]["ErrorDetail"][];
            /**
             * @description Human-readable summary. Not stable; do not parse.
             * @example stack not found
             */
            message: string;
            /**
             * @description Request ID echoed in the X-Request-ID header and the manager logs.
             * @example 4f1c2e7a9b0d4c3e8f6a1b2c3d4e5f60
             */
            requestId: string;
            /** @description True when repeating the identical request later may succeed. */
            retryable: boolean;
        };
        ErrorDetail: {
            /**
             * @description Input location, e.g. body.name, query.limit, path.stackId, header.If-Match.
             * @example body.name
             */
            field: string;
            /**
             * @description What is wrong with the value.
             * @example expected length >= 1
             */
            message: string;
        };
        HealthBody: {
            /** @description Source commit the manager was built from. */
            commit: string;
            /**
             * @description Always ok when the process can serve requests.
             * @enum {string}
             */
            status: "ok";
            /**
             * @description Manager build version.
             * @example 0.0.0-edge
             */
            version: string;
        };
        ReadinessBody: {
            checks: components["schemas"]["ReadinessCheck"][];
            /** @enum {string} */
            status: "ready";
        };
        ReadinessCheck: {
            message?: string;
            /** @example database */
            name: string;
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    "get-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    "get-health-ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
}
