package fscorpus

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/flate"
	"compress/gzip"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/neurekadev/dockyard/internal/testharness"
)

var update = flag.Bool("update", false, "rewrite the committed corpus in test/corpora/fs")

// The committed corpus equals what the generator produces.
func TestCorpusFiles(t *testing.T) {
	root, err := testharness.RepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	dir := filepath.Join(root, filepath.FromSlash(CorpusDir))
	if *update {
		if err := WriteCorpus(dir); err != nil {
			t.Fatal(err)
		}
	}
	files, err := Files()
	if err != nil {
		t.Fatal(err)
	}
	for name, want := range files {
		got, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Errorf("%s: %v (run: go test ./internal/testutil/fscorpus -run TestCorpusFiles -update)", name, err)
			continue
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s is stale (run: go test ./internal/testutil/fscorpus -run TestCorpusFiles -update)", name)
		}
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if _, ok := files[e.Name()]; !ok {
			t.Errorf("%s/%s is not generated by fscorpus", CorpusDir, e.Name())
		}
	}
}

func TestTraversalCases(t *testing.T) {
	names := map[string]bool{}
	cats := map[string]int{}
	for _, c := range TraversalCases() {
		if names[c.Name] {
			t.Errorf("duplicate case %s", c.Name)
		}
		names[c.Name] = true
		cats[c.Category]++
		if c.Path == "" {
			t.Errorf("%s: empty path", c.Name)
		}
	}
	for _, cat := range []string{CatDotDot, CatEncoded, CatDoubleEncoded, CatOverlongUTF8, CatUnicode, CatAbsolute, CatBackslash, CatNUL, CatMixed} {
		if cats[cat] == 0 {
			t.Errorf("no cases in category %s", cat)
		}
	}
}

// Reference consumer: os.Root keeps every traversal case inside, while a
// naive filepath.Join escapes (so the corpus is not vacuous).
func TestTraversalContainedByOSRoot(t *testing.T) {
	base := t.TempDir()
	rootDir := filepath.Join(base, "root")
	if err := os.MkdirAll(filepath.Join(rootDir, "a", "b"), 0o755); err != nil {
		t.Fatal(err)
	}
	const secret = "TRAVERSAL-SECRET"
	if err := os.WriteFile(filepath.Join(base, "secret.txt"), []byte(secret), 0o644); err != nil {
		t.Fatal(err)
	}
	root, err := os.OpenRoot(rootDir)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()

	naiveEscapes := 0
	for _, c := range TraversalCases() {
		if f, err := root.Open(c.Path); err == nil {
			b, _ := io.ReadAll(f)
			_ = f.Close()
			if string(b) == secret {
				t.Errorf("%s (%q): os.Root returned the outside secret", c.Name, c.Path)
			}
		}
		if b, err := os.ReadFile(filepath.Join(rootDir, c.Path)); err == nil && string(b) == secret {
			naiveEscapes++
		}
	}
	if naiveEscapes == 0 {
		t.Error("no case escapes a naive filepath.Join; the corpus lost its dot-dot cases")
	}
}

func TestZipSlipEntries(t *testing.T) {
	zr, err := zip.NewReader(bytes.NewReader(ZipSlip()), int64(len(ZipSlip())))
	if err != nil {
		t.Fatal(err)
	}
	root, err := os.OpenRoot(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	hostile := 0
	for _, f := range zr.File {
		if !strings.Contains(f.Name, "..") && !strings.HasPrefix(f.Name, "/") && !strings.Contains(f.Name, ":") {
			continue
		}
		hostile++
		// Reference: os.Root refuses to create escaping entries (names with
		// backslashes or drive letters are literal names on Unix, so they
		// may be created inside the root, which is still contained).
		if w, err := root.Create(f.Name); err == nil {
			_ = w.Close()
			if strings.Contains(f.Name, "../") || strings.HasPrefix(f.Name, "/") {
				t.Errorf("os.Root created escaping entry %q", f.Name)
			}
		}
	}
	if hostile < 6 {
		t.Errorf("zip-slip has %d hostile entries, want >= 6", hostile)
	}
}

func TestTarSlipEntries(t *testing.T) {
	tr := tar.NewReader(bytes.NewReader(TarSlip()))
	seen := map[byte]int{}
	var names []string
	for {
		h, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
		seen[h.Typeflag]++
		names = append(names, h.Name)
	}
	if seen[tar.TypeSymlink] != 2 || seen[tar.TypeLink] != 2 || seen[tar.TypeChar] != 1 {
		t.Errorf("entry types = %v", seen)
	}
	joined := strings.Join(names, "\n")
	for _, want := range []string{"../evil-parent.txt", "/tmp/evil-absolute.txt", "escape-abs/evil-through-abs-symlink.txt", "escape-up/evil-through-rel-symlink.txt"} {
		if !strings.Contains(joined, want) {
			t.Errorf("tar-slip lacks %q", want)
		}
	}
}

func TestBombsInflateAsDeclared(t *testing.T) {
	for _, a := range Archives() {
		if a.UncompressedSize == 0 {
			continue
		}
		t.Run(a.Name, func(t *testing.T) {
			if ratio := a.UncompressedSize / int64(len(a.Data)); ratio < 100 {
				t.Errorf("compression ratio %d:1 is too low for a bomb", ratio)
			}
			var got int64
			switch a.Name {
			case "bomb-ratio.zip":
				got = inflateZip(t, a.Data)
			case "bomb-lying-size.zip":
				zr, err := zip.NewReader(bytes.NewReader(a.Data), int64(len(a.Data)))
				if err != nil {
					t.Fatal(err)
				}
				f := zr.File[0]
				if f.UncompressedSize64 != 16 {
					t.Errorf("declared size = %d, want the lie 16", f.UncompressedSize64)
				}
				// A careful reader (Go's archive/zip) refuses to read past
				// the declared size ...
				rc, err := f.Open()
				if err != nil {
					t.Fatal(err)
				}
				if _, err := io.Copy(io.Discard, rc); err == nil {
					t.Error("archive/zip read past the declared size without an error")
				}
				_ = rc.Close()
				// ... but the raw stream really inflates to the bomb size.
				raw, err := f.OpenRaw()
				if err != nil {
					t.Fatal(err)
				}
				got, err = io.Copy(io.Discard, flate.NewReader(raw))
				if err != nil {
					t.Fatal(err)
				}
			case "bomb.tar.gz":
				gr, err := gzip.NewReader(bytes.NewReader(a.Data))
				if err != nil {
					t.Fatal(err)
				}
				tr := tar.NewReader(gr)
				if _, err := tr.Next(); err != nil {
					t.Fatal(err)
				}
				got, err = io.Copy(io.Discard, tr)
				if err != nil {
					t.Fatal(err)
				}
			case "bomb-nested.zip":
				zr, err := zip.NewReader(bytes.NewReader(a.Data), int64(len(a.Data)))
				if err != nil {
					t.Fatal(err)
				}
				for _, f := range zr.File {
					rc, err := f.Open()
					if err != nil {
						t.Fatal(err)
					}
					inner, err := io.ReadAll(rc)
					_ = rc.Close()
					if err != nil {
						t.Fatal(err)
					}
					got += inflateZip(t, inner)
				}
			default:
				t.Fatalf("no inflation check for %s", a.Name)
			}
			if got != a.UncompressedSize {
				t.Errorf("inflated %d bytes, declared %d", got, a.UncompressedSize)
			}
		})
	}
	if n := len(ZipManyEntries(1000)); n == 0 {
		t.Error("ZipManyEntries produced nothing")
	}
}

func inflateZip(t *testing.T, data []byte) int64 {
	t.Helper()
	zr, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		t.Fatal(err)
	}
	var total int64
	for _, f := range zr.File {
		rc, err := f.Open()
		if err != nil {
			t.Fatal(err)
		}
		n, err := io.Copy(io.Discard, rc)
		_ = rc.Close()
		if err != nil {
			t.Fatal(err)
		}
		total += n
	}
	return total
}

// Reference consumer: os.Root refuses every escaping symlink, follows the
// legitimate ones, fails cleanly on loops and dangling links; hardlinks
// need an inode check.
func TestEscapeTreeWithOSRoot(t *testing.T) {
	et := MustEscapeTree(t)
	root, err := os.OpenRoot(et.Root)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	secretInfo, err := os.Stat(filepath.Join(et.Outside, "secret.txt"))
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range et.Cases {
		t.Run(c.Path, func(t *testing.T) {
			b, err := readRoot(root, c.Path)
			switch {
			case c.Kind == KindHardlink:
				if err != nil || string(b) != et.Secret {
					t.Fatalf("hardlink read = %q, %v", b, err)
				}
				fi, err := root.Stat(c.Path)
				if err != nil || !os.SameFile(fi, secretInfo) {
					t.Errorf("hardlink not detectable via os.SameFile: %v", err)
				}
			case c.Escapes:
				if err == nil {
					t.Errorf("os.Root followed escaping %s (read %q)", c.Path, b)
				}
			case c.Kind == KindSymlink && (strings.HasPrefix(c.Path, "loop") || c.Path == "dangling"):
				if err == nil {
					t.Errorf("%s: read succeeded", c.Path)
				}
			default:
				if err != nil {
					t.Errorf("legitimate %s: %v", c.Path, err)
				}
			}
			if string(b) == et.Secret && c.Kind != KindHardlink {
				t.Errorf("%s leaked the outside secret", c.Path)
			}
		})
	}
	if len(et.Escaping()) < 6 {
		t.Errorf("only %d escaping cases", len(et.Escaping()))
	}
}

// readRoot reads a file (or lists a directory) through root.
func readRoot(root *os.Root, p string) ([]byte, error) {
	f, err := root.Open(filepath.FromSlash(p))
	if err != nil {
		return nil, err
	}
	defer f.Close()
	fi, err := f.Stat()
	if err != nil {
		return nil, err
	}
	if fi.IsDir() {
		names, err := f.Readdirnames(-1)
		return []byte(strings.Join(names, "\n")), err
	}
	return io.ReadAll(f)
}

// The swapper reproduces a TOCTOU escape deterministically for a naive
// consumer that checks the directory and then opens a path below it.
func TestSwapperDeterministic(t *testing.T) {
	et := MustEscapeTree(t)
	if err := os.WriteFile(filepath.Join(et.Outside, "nested.txt"), []byte(et.Secret), 0o644); err != nil {
		t.Fatal(err)
	}
	dir := filepath.Join(et.Root, "dir")
	s, err := NewSwapper(dir, et.Outside)
	if err != nil {
		t.Fatal(err)
	}
	// "check": dir is a real directory inside the root.
	if fi, err := os.Lstat(dir); err != nil || !fi.IsDir() {
		t.Fatalf("check failed: %v", err)
	}
	if err := s.Swap(); err != nil {
		t.Fatal(err)
	}
	// "use": the naive open follows the swapped-in symlink.
	b, err := os.ReadFile(filepath.Join(dir, "nested.txt"))
	if err != nil || string(b) != et.Secret {
		t.Fatalf("naive use after swap = %q, %v; want the outside secret", b, err)
	}
	// os.Root refuses the same path while swapped.
	root, err := os.OpenRoot(et.Root)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	if _, err := readRoot(root, "dir/nested.txt"); err == nil {
		t.Error("os.Root followed the swapped symlink")
	}
	if err := s.Restore(); err != nil {
		t.Fatal(err)
	}
	if b, err := os.ReadFile(filepath.Join(dir, "nested.txt")); err != nil || string(b) != "nested\n" {
		t.Errorf("after restore = %q, %v", b, err)
	}
	if s.Swapped() || s.Flips() != 2 {
		t.Errorf("swapped=%v flips=%d", s.Swapped(), s.Flips())
	}
}

// A contained consumer never observes outside data while the directory
// is being swapped concurrently.
func TestRaceWhileContainedConsumer(t *testing.T) {
	et := MustEscapeTree(t)
	if err := os.WriteFile(filepath.Join(et.Outside, "nested.txt"), []byte(et.Secret), 0o644); err != nil {
		t.Fatal(err)
	}
	root, err := os.OpenRoot(et.Root)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	res, err := RaceWhile(filepath.Join(et.Root, "dir"), et.Outside, 200, 50, time.Minute, func() error {
		b, err := readRoot(root, "dir/nested.txt")
		if err != nil {
			return err
		}
		if string(b) == et.Secret {
			return fmt.Errorf("read outside data: %w", ErrEscaped)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if res.Attempts < 200 || res.Flips < 50 {
		t.Errorf("race too small: %+v", res)
	}
	// The directory is restored afterwards.
	if fi, err := os.Lstat(filepath.Join(et.Root, "dir")); err != nil || !fi.IsDir() {
		t.Errorf("dir not restored: %v", err)
	}
	t.Logf("race: %+v", res)
}
