package diagnostics

import (
	"archive/zip"
	"context"
	"encoding/json"
	"io"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/neurekadev/dockyard/internal/domain"
	"github.com/neurekadev/dockyard/internal/manager/api"
	"github.com/neurekadev/dockyard/internal/manager/audit"
	"github.com/neurekadev/dockyard/internal/manager/store"
	"github.com/neurekadev/dockyard/internal/protocol"
)

// Minimum Engine (#25 Q2): Docker 25.0, API 1.44.
const minEngineAPI = "1.44"

const bundleReadme = `DockYard support bundle (#34)

Generated by the instance owner for troubleshooting. It never contains
secret values: no passwords, tokens, keys, registry/Git/S3 credentials,
Recovery Key, TOTP seeds, Compose or .env contents, file contents or job
inputs. Configuration lists values the operator set; secrets are files
whose paths only are shown. Log lines are the manager's recent structured
log (in memory, bounded) with a second redaction pass.

Files:
  versions.json        manager build, API and agent protocol versions, every agent's version
  configuration.json   effective configuration (DOCKYARD_* settings, redacted)
  support-matrix.json  per-environment checks against the supported host boundary
  agents.json          environments and agents: status, connection, version compatibility
  audit-chain.json     result of verifying the audit hash chain
  jobs.json            job queue summary (counts per kind and state, unfinished jobs)
  database.json        schema migrations, pre-migration snapshots, database sizes
  logs.ndjson          recent manager log lines, oldest first
`

// bundleVersions is versions.json.
type bundleVersions struct {
	GeneratedAt          time.Time      `json:"generatedAt"`
	Manager              map[string]any `json:"manager"`
	APIVersion           string         `json:"apiVersion"`
	AgentProtocolVersion string         `json:"agentProtocolVersion"`
	AgentVersionWindow   string         `json:"agentVersionWindow"`
	Agents               []bundleAgent  `json:"agents"`
}

type bundleAgent struct {
	AgentID         string     `json:"agentId"`
	EnvironmentID   string     `json:"environmentId"`
	EnvironmentName string     `json:"environmentName,omitempty"`
	Status          string     `json:"status"`
	Connected       bool       `json:"connected"`
	Version         string     `json:"version"`
	Compatibility   string     `json:"compatibility,omitempty"`
	RotationPending bool       `json:"rotationPending,omitempty"`
	LastConnectedAt *time.Time `json:"lastConnectedAt,omitempty"`
	LastSeenAt      *time.Time `json:"lastSeenAt,omitempty"`
	RevokedReason   string     `json:"revokedReason,omitempty"`
	Engine          string     `json:"engine,omitempty"`
	EngineAPI       string     `json:"engineApi,omitempty"`
	OS              string     `json:"os,omitempty"`
	Arch            string     `json:"arch,omitempty"`
	PlainHTTP       bool       `json:"plainHttp,omitempty"`
	Diagnostics     []string   `json:"diagnostics,omitempty"`
}

type bundleEnvironment struct {
	ID                  string     `json:"id"`
	Name                string     `json:"name"`
	Status              string     `json:"status"`
	Online              bool       `json:"online"`
	AgentID             string     `json:"agentId,omitempty"`
	ConnectionChangedAt *time.Time `json:"connectionChangedAt,omitempty"`
	ArchivedAt          *time.Time `json:"archivedAt,omitempty"`
}

type supportCheck struct {
	Check  string `json:"check"`
	Status string `json:"status" enum:"ok,warning,unsupported,unknown"`
	Detail string `json:"detail,omitempty"`
}

type environmentSupport struct {
	EnvironmentID string         `json:"environmentId"`
	Name          string         `json:"name"`
	Checks        []supportCheck `json:"checks"`
}

// WriteSupportBundle streams the support bundle as a zip to w. It reads
// only allowlisted fields; see bundleReadme for the contents.
func (s *Service) WriteSupportBundle(ctx context.Context, w io.Writer) error {
	now := s.o.Clock.Now().UTC()
	envs, err := s.o.Environments.ListEnvironments(ctx, domain.EnvironmentFilter{
		Statuses: []domain.EnvironmentStatus{domain.EnvironmentActive, domain.EnvironmentArchived}})
	if err != nil {
		return err
	}
	agents, err := s.o.Environments.ListAgents(ctx, domain.AgentFilter{})
	if err != nil {
		return err
	}
	connected := map[string]bool{}
	if s.o.Sessions != nil {
		for _, id := range s.o.Sessions() {
			connected[id] = true
		}
	}
	names := map[string]string{}
	for _, e := range envs {
		names[e.ID] = e.Name
	}

	zw := zip.NewWriter(w)
	add := func(name string, write func(io.Writer) error) error {
		f, err := zw.CreateHeader(&zip.FileHeader{Name: name, Method: zip.Deflate, Modified: now})
		if err != nil {
			return err
		}
		return write(f)
	}
	addJSON := func(name string, v any) error {
		return add(name, func(f io.Writer) error {
			enc := json.NewEncoder(f)
			enc.SetIndent("", "  ")
			return enc.Encode(v)
		})
	}
	if err := add("README.txt", func(f io.Writer) error { _, err := io.WriteString(f, bundleReadme); return err }); err != nil {
		return err
	}

	b := s.o.Build
	versions := bundleVersions{GeneratedAt: now,
		Manager:    map[string]any{"version": b.Version, "commit": b.Commit, "date": b.Date, "goVersion": b.GoVersion},
		APIVersion: api.Version, AgentProtocolVersion: protocol.Version,
		AgentVersionWindow: "same or previous minor release as the manager; newer agents are refused", Agents: []bundleAgent{}}
	var support []environmentSupport
	for _, a := range agents {
		ba := bundleAgent{AgentID: a.ID, EnvironmentID: a.EnvironmentID, EnvironmentName: names[a.EnvironmentID], Status: string(a.Status),
			Connected: a.SessionID != "" && connected[a.EnvironmentID], Version: a.Version, RotationPending: a.RotationPending,
			LastConnectedAt: a.LastConnectedAt, LastSeenAt: a.LastSeenAt, RevokedReason: a.RevokedReason}
		if a.Status == domain.AgentActive {
			ba.Compatibility, _ = protocol.AgentCompatibility(b.Version, a.Version)
		}
		var caps *protocol.CapabilitiesPayload
		if a.Capabilities != "" {
			var c protocol.CapabilitiesPayload
			if json.Unmarshal([]byte(a.Capabilities), &c) == nil {
				caps = &c
				ba.Engine, ba.EngineAPI, ba.OS, ba.Arch, ba.PlainHTTP = c.Engine.Version, c.Engine.APIVersion, c.OS, c.Arch, c.Transport.PlainHTTP
				for _, d := range c.Diagnostics {
					ba.Diagnostics = append(ba.Diagnostics, d.Area+"/"+d.Code)
				}
			}
		}
		versions.Agents = append(versions.Agents, ba)
		if a.Status == domain.AgentActive {
			support = append(support, s.supportChecks(a, caps, names[a.EnvironmentID]))
		}
	}
	if err := addJSON("versions.json", versions); err != nil {
		return err
	}
	if err := addJSON("configuration.json", map[string]any{"settings": s.o.Settings,
		"metricsEndpointEnabled": s.o.MetricsEnabled}); err != nil {
		return err
	}
	if support == nil {
		support = []environmentSupport{}
	}
	if err := addJSON("support-matrix.json", map[string]any{
		"boundary": "Linux amd64/arm64 standalone Docker Engine 25.0 (API 1.44) or newer; rootless Engines, Docker Desktop and NAS " +
			"vendor Engines are unsupported (docs/support-matrix.md)",
		"environments": support}); err != nil {
		return err
	}
	be := make([]bundleEnvironment, 0, len(envs))
	for _, e := range envs {
		be = append(be, bundleEnvironment{ID: e.ID, Name: e.Name, Status: string(e.Status), Online: e.Online, AgentID: e.AgentID,
			ConnectionChangedAt: e.ConnectionChangedAt, ArchivedAt: e.ArchivedAt})
	}
	if err := addJSON("agents.json", map[string]any{"environments": be, "agents": versions.Agents,
		"connectedSessions": len(connected)}); err != nil {
		return err
	}
	if err := addJSON("audit-chain.json", s.auditChain(ctx)); err != nil {
		return err
	}
	jobs, err := s.jobSummary(ctx)
	if err != nil {
		return err
	}
	if err := addJSON("jobs.json", jobs); err != nil {
		return err
	}
	if err := addJSON("database.json", s.database(ctx)); err != nil {
		return err
	}
	if err := add("logs.ndjson", s.writeLogs); err != nil {
		return err
	}
	return zw.Close()
}

// supportChecks evaluates an active agent's report against the supported
// host boundary (#25 Q2, docs/support-matrix.md).
func (s *Service) supportChecks(a domain.Agent, caps *protocol.CapabilitiesPayload, name string) environmentSupport {
	out := environmentSupport{EnvironmentID: a.EnvironmentID, Name: name}
	add := func(check, status, detail string) {
		out.Checks = append(out.Checks, supportCheck{Check: check, Status: status, Detail: detail})
	}
	st, _ := protocol.AgentCompatibility(s.o.Build.Version, a.Version)
	switch st {
	case protocol.VersionCurrent:
		add("agent_version", "ok", a.Version)
	case protocol.VersionOutdated:
		add("agent_version", "warning", a.Version+": previous minor release; upgrade it")
	default:
		add("agent_version", "unsupported", a.Version+": outside the version window; the manager refuses it")
	}
	if caps == nil {
		add("capabilities", "unknown", "the agent has not reported its capabilities yet")
		return out
	}
	switch {
	case caps.Engine.APIVersion == "":
		add("engine_api", "unknown", "no negotiated API version")
	case apiAtLeast(caps.Engine.APIVersion, minEngineAPI):
		add("engine_api", "ok", "Docker "+caps.Engine.Version+", API "+caps.Engine.APIVersion)
	default:
		add("engine_api", "unsupported", "Docker "+caps.Engine.Version+", API "+caps.Engine.APIVersion+" is below the minimum 25.0 / API "+minEngineAPI)
	}
	if caps.OS == "linux" && slices.Contains([]string{"amd64", "arm64"}, caps.Arch) {
		add("platform", "ok", caps.OS+"/"+caps.Arch)
	} else {
		add("platform", "unsupported", caps.OS+"/"+caps.Arch+": only linux/amd64 and linux/arm64 are supported")
	}
	if caps.Engine.Rootless {
		add("rootless", "unsupported", "rootless Engines are unsupported in v1")
	} else {
		add("rootless", "ok", "")
	}
	if s.o.Inventory != nil {
		if inv, ok := s.o.Inventory(a.EnvironmentID); ok {
			if inv.DockerDesktop {
				add("docker_desktop", "unsupported", "Docker Desktop is unsupported in v1")
			} else {
				add("docker_desktop", "ok", "")
			}
		}
	}
	if caps.Transport.PlainHTTP {
		add("transport", "warning", "the agent uses a plain-HTTP internal manager URL")
	} else {
		add("transport", "ok", "")
	}
	if len(caps.Diagnostics) == 0 {
		add("agent_diagnostics", "ok", "")
	}
	for _, d := range caps.Diagnostics {
		add("agent_diagnostics", "unsupported", d.Area+"/"+d.Code)
	}
	return out
}

// apiAtLeast compares "major.minor" API versions.
func apiAtLeast(v, minimum string) bool {
	parse := func(s string) (int, int, bool) {
		maj, mn, ok := strings.Cut(s, ".")
		a, err1 := strconv.Atoi(maj)
		b, err2 := strconv.Atoi(mn)
		return a, b, ok && err1 == nil && err2 == nil
	}
	a1, b1, ok1 := parse(v)
	a2, b2, ok2 := parse(minimum)
	if !ok1 || !ok2 {
		return false
	}
	return a1 > a2 || (a1 == a2 && b1 >= b2)
}

type auditChainResult struct {
	OK        bool                 `json:"ok"`
	Checked   int64                `json:"checked"`
	AnchorSeq int64                `json:"anchorSeq"`
	HeadSeq   int64                `json:"headSeq"`
	Problems  []auditProblemResult `json:"problems"`
	Error     string               `json:"error,omitempty"`
}

type auditProblemResult struct {
	Seq    int64  `json:"seq"`
	Kind   string `json:"kind"`
	Detail string `json:"detail"`
}

func (s *Service) auditChain(ctx context.Context) auditChainResult {
	rep, err := s.o.Audit.Verify(ctx)
	out := auditChainResult{OK: err == nil && rep.OK, Checked: rep.Checked, AnchorSeq: rep.AnchorSeq, HeadSeq: rep.HeadSeq,
		Problems: []auditProblemResult{}}
	for _, p := range rep.Problems {
		out.Problems = append(out.Problems, auditProblemResult{Seq: p.Seq, Kind: p.Kind, Detail: p.Detail})
	}
	if err != nil {
		out.Error = "verification could not run"
	}
	return out
}

type jobCountJSON struct {
	Kind  string `json:"kind"`
	State string `json:"state"`
	Count int    `json:"count"`
}

type unfinishedJobJSON struct {
	ID            string    `json:"id"`
	Kind          string    `json:"kind"`
	State         string    `json:"state"`
	EnvironmentID string    `json:"environmentId,omitempty"`
	Origin        string    `json:"origin"`
	BlockedBy     string    `json:"blockedBy,omitempty"`
	Attempt       int       `json:"attempt"`
	CreatedAt     time.Time `json:"createdAt"`
}

// maxBundleJobs bounds the unfinished jobs listed.
const maxBundleJobs = 200

func (s *Service) jobSummary(ctx context.Context) (map[string]any, error) {
	counts, err := store.CountJobs(ctx, s.o.DB)
	if err != nil {
		return nil, err
	}
	cs := make([]jobCountJSON, 0, len(counts))
	for _, c := range counts {
		cs = append(cs, jobCountJSON{Kind: string(c.Kind), State: string(c.State), Count: c.Count})
	}
	list, err := store.ListJobs(ctx, s.o.DB, domain.JobFilter{States: unfinishedStates, Limit: maxBundleJobs})
	if err != nil {
		return nil, err
	}
	jobs := make([]unfinishedJobJSON, 0, len(list))
	for _, j := range list { // never the input, items or messages
		jobs = append(jobs, unfinishedJobJSON{ID: j.ID, Kind: string(j.Kind), State: string(j.State), EnvironmentID: j.EnvironmentID,
			Origin: string(j.Origin), BlockedBy: j.BlockedBy, Attempt: j.Attempt, CreatedAt: j.CreatedAt})
	}
	return map[string]any{"counts": cs, "unfinished": jobs}, nil
}

func (s *Service) database(ctx context.Context) map[string]any {
	out := map[string]any{"mainBytes": fileSize(s.o.DatabasePath), "metricsBytes": fileSize(s.o.MetricsPath)}
	if s.o.Migrations != nil {
		applied, pending, err := store.Status(ctx, s.o.DB, s.o.Migrations)
		if err != nil {
			out["migrationsError"] = "cannot read the migration status"
		}
		out["migrationsApplied"] = len(applied)
		if len(applied) > 0 {
			out["newestMigration"] = applied[len(applied)-1]
		}
		out["migrationsPending"] = pending
	}
	snaps, err := store.ListSnapshots(s.o.SnapshotDir)
	if err == nil {
		if snaps == nil {
			snaps = []string{}
		}
		out["preMigrationSnapshots"] = snaps
	}
	return out
}

// writeLogs writes the retained log lines, each passed through the audit
// redaction layer again (sensitive keys, secret-shaped values, long
// strings), oldest first.
func (s *Service) writeLogs(w io.Writer) error {
	if s.o.Logs == nil {
		return nil
	}
	lines, dropped := s.o.Logs.Lines()
	enc := json.NewEncoder(w)
	if dropped > 0 {
		if err := enc.Encode(map[string]any{"msg": "older log lines were dropped", "dropped": dropped}); err != nil {
			return err
		}
	}
	for _, l := range lines {
		var m map[string]any
		if json.Unmarshal(l, &m) != nil {
			m = map[string]any{"msg": "unparsable log line omitted"}
		}
		if err := enc.Encode(audit.RedactDetails(m)); err != nil {
			return err
		}
	}
	return nil
}
